export default{
    LOGING_BACKGROUND:require('../component/image/login.png'),
    LOGO :require('../component/image/logo.png'),
    PERSON_LOGO:require('../component/image/unknow.png'),
    SETTING_LOGO:require('../component/image/setting.png'),
    PRIVACY_LOGO:require('../component/image/privacy.png'),
    INVITE_LOGO:require('../component/image/invite.png'),
    LOGOUT_LOGO:require('../component/image/logout.png'),
    CHAT_LOGO:require('../component/image/chat.png'),
    NOTIFICATION_LOGO:require('../component/image/notification.png'),
    HELP_LOGO:require('../component/image/help.png'),
    CALL_LOGO:require('../component/image/call.png'),
    PROFILE_LOGO:require('../component/image/profile.png'),
    SENDMSG_LOGO:require('../component/image/send.png'),
    CAMARA_LOGO:require('../component/image/camera.png'),
}